sudo: required
dist: trusty

language: node_js
node_js:
  - "6.9.5"

notifications:
  email: true

branches:
  only:
    - master

cache: yarn

script:
  - ionic build
  - npm run lint
  - node node_modules/karma/bin/karma start ./karma.conf.js --single-run

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - cd GATEWAY
  - npm install -g cordova ionic typescript tslint angular-cli karma yarn
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

