
sudo: false
language: node_js
node_js:
  - "iojs"

notifications:
  email: true

cache: yarn

script:
  - npm run lint
  - npm test

before_install:
  - cd GATEWAY
  - npm install -g cordova ionic typescript

before_script:
  - npm install
