

language: node_js
node_js:
  - "iojs"

notifications:
  email: true

branches:
  only:
    - master
    - Travis


cache: yarn

script:
  - ionic build
  - npm run lint
  - npm test

before_install:
  - cd GATEWAY
  - npm install -g cordova ionic typescript tslint angular-cli karma
  — export CHROME_BIN=chromium-browser
  — export DISPLAY=:99.0
  — sh -e /etc/init.d/xvfb start

apt:
  sources:
    — google-chrome
  packages:
    — google-chrome-stable
    — google-chrome-beta

before_script:
  - npm install
  - ng build

