
sudo: false
language: node_js
node_js:
  - "iojs"
  - "7"
  - "6"

notifications:
  email: true

cache: yarn

script:
  - npm run lint
  - npm test

before_install:
  - cd GATEWAY
  - npm install -g cordova ionic typescript
