

language: node_js
node_js:
  - "6.9.5"

notifications:
  email: true

branches:
  only:
    - master
    - Travis


cache: yarn

script:
  - ionic build
  - npm run lint
  - npm test

before_install:
  - cd GATEWAY
  - npm install -g cordova ionic typescript tslint angular-cli karma yarn

before_script:
  - npm install
